# Generated by Django 4.0.1 on 2022-01-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image1',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
