# Generated by Django 4.0.1 on 2022-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_report_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
