# Generated by Django 4.0.1 on 2022-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_report_image1_alter_report_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='audio',
            field=models.FileField(null=True, upload_to='audios'),
        ),
        migrations.AddField(
            model_name='report',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
