# Generated by Django 4.0.1 on 2022-01-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_officials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Officials',
            new_name='Official',
        ),
    ]
