# Generated by Django 4.0.1 on 2022-02-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_rename_officials_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=20, null=True),
        ),
    ]
