# Generated by Django 4.0.1 on 2022-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True),
        ),
    ]
