# Generated by Django 4.0.1 on 2022-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=200)),
                ('lga', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
