# Generated by Django 4.0.1 on 2022-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_notification_options_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='audio',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='image1',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='image2',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='image3',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='video',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
