# Generated by Django 4.0.1 on 2022-03-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_safetripreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetripreport',
            name='message',
        ),
        migrations.AddField(
            model_name='safetripreport',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='safetripreport',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True),
        ),
    ]
